@startuml
title Paketni Diagram

package "Home Assistant" <<aplikacija>> {

    package "UporabniškiVmesnik"
    package "Store" <<shramba>>
    package "Entitete"

    package "Varko" <<podsistem>> {
        package "VarkoPlošča"
        package "UpravljanjeNaprav"
        package "UpravljanjeCon"
        package "UpravljanjeSUS"
        package "UpravljanjeStanj"
        package "UpravljanjeRadioPostaje"
    }

}

package "Zunanji sistemi" {
     package "Frigate"
     package "MQTT"
}

UporabniškiVmesnik .-> VarkoPlošča : "dostopa"
Varko .-> MQTT : "dostopa"
Frigate .-> MQTT : "dostopa"
UpravljanjeStanj --> UpravljanjeNaprav : "proži"
UpravljanjeCon --> UpravljanjeStanj : "proži"
UpravljanjeCon --> UpravljanjeSUS : "proži"
VarkoPlošča --> UpravljanjeNaprav : "proži"
VarkoPlošča --> UpravljanjeCon : "proži"
VarkoPlošča --> UpravljanjeSUS : "proži"
VarkoPlošča --> UpravljanjeStanj : "proži"
VarkoPlošča --> UpravljanjeRadioPostaje : "proži"
UpravljanjeNaprav .-> Entitete : "dostopa"
UpravljanjeNaprav --> UpravljanjeRadioPostaje : "proži"
UpravljanjeSUS .-> Entitete : "dostopa"
UpravljanjeCon .-> Entitete : "dostopa"
Varko .-> Store : "dostopa"
@enduml
