@startuml
node "Docker Host" as dockerHost <<izvajalno okolje>> {

    node "Docker Compose" as dockerCompose <<koordinator izvajanja>> {

        node "Home Assistant" as haContainer <<vsebnik>> {
            artifact "Home Assistant Slika" as haImage
            artifact "Varko Komponenta" as varkoComponent
        }

        node "MQTT Broker" as mqttContainer <<vsebnik>> {
            artifact "Mosquitto Slika" as mosquittoImage
            artifact "mosquitto.conf" as mosquittoConfig
        }

        node "Frigate" as frigateContainer <<vsebnik>> {
            artifact "Frigate Slika" as frigateImage
            artifact "config.yaml" as frigateConfig
        }
    }
}

node "Brskalnik" as haWebUI <<izvajalno okolje>> {
    artifact "Spletni Home Assistant Vmesnik"
}

node "Telefon" as mobileDevice <<izvajalno okolje>> {
    artifact "Home Assistant Aplikacija"
}

haWebUI --> dockerHost : <<HTTP/S>>
mobileDevice --> dockerHost : <<HTTP/S>>
haContainer <--> mqttContainer : <<MQTT>>
frigateContainer --> mqttContainer : <<MQTT>>
haImage ..> varkoComponent : <<uporablja>>
mosquittoImage ..> mosquittoConfig : <<uporablja>>
frigateImage ..> frigateConfig : <<uporablja>>
@enduml
