@startuml
title Paketni Diagram

package "Home Assistant" <<aplikacija>> {

    package "UporabniškiVmesnik"
    package "Store" <<shramba>>
    package "Entitete"

    package "Varko" <<podsistem>> {
        package "VarkoPlošča"
        package "UpravljanjeNaprav"
        package "UpravljanjeCon"
        package "UpravljanjeSUS"
        package "UpravljanjeStanj"
    }

}

package "Zunanji sistemi" {
     package "Frigate"
     package "MQTT"
}

UporabniškiVmesnik .-> VarkoPlošča
Varko .-> "Zunanji sistemi"
UpravljanjeStanj --> UpravljanjeNaprav
UpravljanjeCon --> UpravljanjeStanj
UpravljanjeCon --> UpravljanjeSUS
VarkoPlošča --> UpravljanjeNaprav
VarkoPlošča --> UpravljanjeCon
VarkoPlošča --> UpravljanjeSUS
VarkoPlošča --> UpravljanjeStanj
UpravljanjeNaprav .-> Entitete
UpravljanjeSUS .-> Entitete
UpravljanjeCon .-> Entitete
Varko .-> Store
@enduml
