services:
  homeassistant_dev:
    image: homeassistant/home-assistant:latest
    container_name: homeassistant_dev
    volumes:
      - .run/dev/home-assistant/config:/config
    environment:
      - TZ=Europe/Ljubljana
    ports:
      - "8123:8123" # Home Assistant web UI
    networks:
      - varko_dev
    profiles:
      - dev
    restart: unless-stopped

  frigate_dev:
    image: ghcr.io/blakeblackshear/frigate:stable
    container_name: frigate_dev
    volumes:
      - .run/dev/frigate/config:/config
    shm_size: "512m"
    ports:
      - "5000:5000" # Frigate web UI
      - "8554:8554" # RTSP stream
    networks:
      - varko_dev
    profiles:
      - dev
    restart: unless-stopped

  mqtt_broker_dev:
    image: eclipse-mosquitto:latest
    container_name: mqtt_broker_dev
    volumes:
      - .run/dev/mqtt/mosquitto:/mosquitto
    ports:
      - "1883:1883"
    networks:
      - varko_dev
    profiles:
      - dev
    restart: unless-stopped

networks:
  varko_dev:
