# Group management
add_person:
  name: Add person
  description: Add a person to the varko group
  fields:
    person:
      description: Person entity
      required: true
      example: person.john
      selector:
        entity:
          domain: person

remove_person:
  name: Remove person
  description: Remove a person from the varko group
  fields:
    person:
      description: Person entity
      required: true
      example: person.john
      selector:
        entity:
          domain: person

# Device management services
add_light_device:
  name: Add Light Device
  description: Add a device to be controlled by the presence simulation system
  fields:
    entity:
      name: Shelly Entity
      description: Link an existing Shelly device instead of creating a new one
      required: false
      selector:
        entity:
          domain: light
          integration: shelly
    device_name:
      name: Device Name
      description: The name of the device to be added
      required: true
      example: "Living Room Light"
      selector:
        text:
    is_enabled:
      name: Enabled
      description: Immediately activate this device
      required: false
      default: true
      selector:
        boolean:
    device_id:
      name: Device Id
      description: Id of the device to be added
      required: true
      example: "fcfbs2..."
      selector:
        text:

add_media_device:
  name: Add Media Device
  description: Add a media device to be controlled by the presence simulation system
  fields:
    entity:
      name: Media Entity
      description: Link an existing media device instead of creating a new one
      required: true
      selector:
        entity:
          domain: media_player
          integration: cast
    is_enabled:
      name: Enabled
      description: Immediately activate this device
      required: false
      default: true
      selector:
        boolean:

remove_device:
  name: Remove Device
  description: Remove a device from the presence simulation system
  fields:
    entity:
      name: Device To Remove
      description: Select the device to remove
      required: true
      selector:
        entity:   
          filter:
            - domain: light
            - integration:
                - varko
                - shelly
                - cast
            - domain: media_player
enable_device:
  name: Enable Device
  description: Enable a device for use in the presence simulation system
  fields:
    entity:
      name: Device To Enable
      description: Unique identifier for the device to enable
      required: true
      selector:
        entity:
          filter:
            - domain: light
            - integration:
                - varko
                - shelly
                - cast
            - domain: media_player

disable_device:
  name: Disable Device
  description: Disable a device from being used in the presence simulation system
  fields:
    entity:
      name: Device To Disable
      description: Unique identifier for the device to disable
      required: true
      selector:
        entity:
          filter:
            - domain: light
            - integration:
                - varko
                - shelly
                - cast
            - domain: media_player

choose_radio_station:
  name: Choose Radio Station
  description: Choose a radio station used by media devices in the presence simulation system
  fields:
    radio_country_code:
      name: Radio Country Code
      description: The country code of the radio station to play
      required: true
      example: "SI"
      selector:
        text:
    station_name:
      name: Station Name
      description: The name of the radio station to play
      required: true
      example: "Radio 1"
      selector:
        text:

get_list_of_stations_per_country:
  name: Get List of Stations Per Country
  description: Get a list of radio stations per country
  fields:
    radio_country_code:
      name: Radio Country Code
      description: The country code to get the list of stations for
      required: true
      example: "SI"
      selector:
        text:

# System state services
set_state_idle:
  name: Set state to idle
  description: Set system to idle state
  fields: {}

set_state_ready:
  name: Set state to ready
  description: Set system to ready state
  fields: {}

set_state_active:
  name: Set state to active
  description: Set system to active state
  fields: {}

# Location zone management
select_activation_zone:
  name: Select Activation Zone
  description: Select a location zone for system activation
  fields:
    zone_entity_id:
      name: Zone ID
      description: Identifier for the zone to select
      required: true
      example: "zone.home"
      selector:
        entity:
          domain: zone
