# Group management
add_person:
  name: Add person
  description: Add a person to the varko group
  fields:
    person:
      description: Person entity
      required: true
      example: person.john
      selector:
        entity:
          domain: person

remove_person:
  name: Remove person
  description: Remove a person from the varko group
  fields:
    person:
      description: Person entity
      required: true
      example: person.john
      selector:
        entity:
          domain: person

# Device management services
add_device:
  name: Add Device
  description: Add a device to be controlled by the presence simulation system
  fields:
    entity:
      name: Shelly Entity
      description: Link an existing Shelly device instead of creating a new one
      required: false
      selector:
        entity:
          domain: light
          integration: shelly
    device_type:
      name: Device Type
      description: The type of the device to be added
      required: true
      example: "light"
      selector:
        select:
          options:
            - "light"
    device_name:
      name: Device Name
      description: The name of the device to be added
      required: true
      example: "Living Room Light"
      selector:
        text:
    is_enabled:
      name: Enabled
      description: Immediately activate this device
      required: false
      default: true
      selector:
        boolean:
    device_id:
      name: Device Id
      description: Id of the device to be added
      required: true
      example: "fcfbs2..."
      selector:
        text:

remove_device:
  name: Remove Device
  description: Remove a device from the presence simulation system
  fields:
    entity:
      name: Device To Remove
      description: Select the device to remove
      required: true
      selector:
        entity:
          domain: light
          filter:
            - integration: varko
            - integration: shelly

enable_device:
  name: Enable Device
  description: Enable a device for use in the presence simulation system
  fields:
    entity:
      name: Device To Enable
      description: Unique identifier for the device to enable
      required: true
      selector:
        entity:
          domain: light
          filter:
            - integration: varko
            - integration: shelly

disable_device:
  name: Disable Device
  description: Disable a device from being used in the presence simulation system
  fields:
    entity:
      name: Device To Disable
      description: Unique identifier for the device to disable
      required: true
      selector:
        entity:
          domain: light
          filter:
            - integration: varko
            - integration: shelly

# System state services
set_state_idle:
  name: Set state to idle
  description: Set system to idle state
  fields: {}

set_state_ready:
  name: Set state to ready
  description: Set system to ready state
  fields: {}

set_state_active:
  name: Set state to active
  description: Set system to active state
  fields: {}

# Location zone management
add_activation_zone:
  name: Add Activation Zone
  description: Add a location zone where the system should activate when all users leave
  fields:
    zone_id:
      name: Zone ID
      description: Identifier for the zone to add
      required: true
      example: "zone.home"
      selector:
        entity:
          domain: zone

remove_activation_zone:
  name: Remove Activation Zone
  description: Remove a location zone from system activation
  fields:
    zone_id:
      name: Zone ID
      description: Identifier for the zone to remove
      required: true
      example: "zone.home"
      selector:
        entity:
          domain: zone

# Notification service
send_notification:
  name: Send Notification
  description: Send a notification about system status or detected intruders
  fields:
    message:
      name: Message
      description: The notification message to send
      required: true
      example: "Intruder detected in living room"
      selector:
        text:
    recipients:
      name: Recipients
      description: List of persons to notify (empty = all configured users)
      required: false
      example: ["person.john", "person.jane"]
      selector:
        text:
