@startuml

node "Vsebnik Docker - Home Assistant" as HA {
  frame "Integracija" as INTEGRACIJA {
    [Poslovna logika] as LOGIKA
  }
  database "Uporabniške nastavitve" as NASTAVITVE
}

node "Vsebnik Docker - Frigate" as DOCKERFRIGATE {
  [Prepoznava ljudi v video prenosu] as PREPOZNAVA
}

node "Vsebnik Docker - MQTT" as DOCKERMQTT {
  [MQTT posrednik] as MQTT
}

actor Uporabnik as UPORABNIK

cloud "Kamera" as KAMERA
cloud "Pametne luči / pametna televzija" as PORABNIKI
cloud "Mobilna aplikacija Home Assistant" as APLIKACIJA

LOGIKA -- NASTAVITVE : Upravljanje sistema

APLIKACIJA --> HA : Lokacija uporabnikov

KAMERA --> PREPOZNAVA : Video prenos (RTSP)
PREPOZNAVA --> MQTT : Signali prepoznave ljudi (MQTT)
MQTT --> PORABNIKI : Upravljanje pametnih naprav (MQTT)

LOGIKA <-- MQTT : Signali prepoznave ljudi (MQTT)
LOGIKA --> MQTT : Komunikacija z napravami (MQTT)

UPORABNIK --> APLIKACIJA
UPORABNIK --> NASTAVITVE
UPORABNIK --> LOGIKA : Ročno upravljanje sistema

@enduml