mqtt:
  enabled: true
  host: mqtt_broker_dev
  port: 1883
  topic_prefix: frigate_dev

cameras:
  camera1:
    ffmpeg:
      inputs:
        - path: rtsp://0.0.0.0:8533/stream # RTSP stream URL
          roles:
            - detect
    objects:
      track:
        - person
    snapshots:
      enabled: false
    motion:
      mask: []
version: 0.15-1
