mqtt:
  enabled: false

cameras:
  camera1:
    ffmpeg:
      inputs:
        - path: rtsp://0.0.0.0:8553/stream # RTSP stream URL
          roles:
            - detect
    objects:
      track:
        - person
    motion:
      mask: []
version: 0.15-1
