name: PR

on:
  pull_request:
    branches:
      - main

jobs:
  tidy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Check formatting
        run: make format

      - name: Check for uncommitted changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Repository is not formatted. Please run 'make format' and commit the changes."
            exit 1
          fi

      - name: Run tests
        run: make test
